import Head from "next/head"
import { useEffect } from "react"
//  import Link from 'next/link'

import styles from "styles/Home.module.css"
import { colors } from "styles/theme"

import Avatar from "components/Avatar"
import Button from "components/Button/button"
import GitHub from "components/Icons/Github"
import { Logo } from "Components/Icons/Logo"

import { loginWithGitHub } from "../firebase/client"
import { useRouter } from "next/router"
import useUser, { USER_STATE } from "hooks/useUser"

export default function Home() {
  const user = useUser()
  const router = useRouter()
  console.log(`I AM IN THE user${user}`)

  useEffect(() => {
    user && router.replace("/home")
  })
  const handleClick = () => {
    loginWithGitHub().catch((error) => {
      console.log(error)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        {console.log("I AM IN THE HEADER")}
        <title>👨🏻‍🚀🆉🅸🅷🅾!</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log("I AM IN THE AppLayout")}
      <section>
        <Logo width="150" />
        <h1>Welcome to Ziho!</h1>
        <h2>Zihoniens are the citizens from Ziho!</h2>
        <div>
          {/* In the code below you can see that if the user is null,
        The button of Github Login is displayed.
        If the user is not null and not undefined the userWelcomeDiv
        is displayed.
        Otherwise/whatsgon bruh! */}
          {user === USER_STATE.NOT_AUTHENTICATED ? (
            <Button onClick={handleClick}>
              {console.log("I AM IN THE Button")}
              <GitHub fill="#fff" width={24} height={24} />
              Login with Github
            </Button>
          ) : user && user.avatar ? (
            <div
              className="userWelcomeDiv"
              style={styles.container}
            >
              {console.log(
                `I AM IN THE userWelcomeDiv ${user.email}`
              )}
              <Avatar
                alt={user.username}
                src={user.avatar}
                text={user.email}
                withText={true}
              />
            </div>
          ) : (
            <div className="spinner"></div>
          )}
        </div>
      </section>
      <style jsx>
        {`
          div > img {
            width: 120px;
            height: 120px;
            border-radius: 50%;
          }
          section {
            display: grid;
            height: 100%;
            place-content: center;
            place-items: center;
          }
          h1 {
            color: ${colors.primary};
            font-size: 24px;
          }
          div {
            margin-top: 16px;
          }

          .spinner {
            border: 4px solid rgba(0, 0, 0, 0.1);
            border-left-color: transparent;
            border-radius: 50%;
            width: 36px;
            height: 36px;

            animation: spin 1s linear infinite;
          }
          @keyframes spin {
            0% {
              transform: rotate(0deg);
            }

            100% {
              transform: rotate(360deg);
            }
          }
        `}
      </style>
    </div>
  )
}
